# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Neuro group @ FEMTO-ST"
title:              "Neuro group at the Dept of Automation and Robotics, FEMTO-ST Institute"
description:        "Lab webpage for the Neuro group, a control systems + neurophysiology research lab at the FEMTO-ST Institute, Besançon France"


# URL
url:                https://neuro-team-femto.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name: Home
    href: /
  - name: About
    href: /about
  - name: Research
    href: /research
  - name: Publications
    href: /publications
  - name: Teaching
    href: /teaching
  - name: Outreach
    href: /outreach
  - name: Collaborators
    href: /collaborators
  - name: Contact
    href: /contact


# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
