# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Neuro group @ FEMTO-ST"
title:              "Neuro group at the Dept of Automation and Robotics, FEMTO-ST Institute"
description:        "Lab webpage for the Neuro group, a control systems + neurophysiology research lab at the FEMTO-ST Institute, Besançon France"


# URL
url:                https://neuro-team-femto.github.io
baseurl:            
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "home"
    href:           "/"
  - name:           "about"
    href:           "/about"
  - name:           "publications"
    href:           "/publications"
  - name:           "people"
    href:           "/people"
#  - name:           "blog"
#    href:           "/blog"
  - name:           "resources"
    href:           "/resources"
  - name:           "L&D 2024-25"
    href:           "/learning2425"
  - name:           "(cream) "
    href:           "/cream"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
